### ISSUE TITLE
owasp-zap-scan failing 

### ISSUE THREAD

**Issue by Aaqib041** [rht-labs/owasp-zap-openshift#10]
Hi ,

I am getting below error while running owasp-zap-scan . I am using the Dockerfile from your repo to create image.

**Error :**

2020-07-29 07:32:12,919 Passive scanning complete
2020-07-29 07:32:12,919 Unexpected error: <type 'exceptions.TypeError'>
Traceback (most recent call last):
  File "/zap/zap-full-scan.py", line 337, in main
    num_urls = len(zap.core.urls)
TypeError: object of type 'instancemethod' has no len()
2020-07-29 07:32:12,920 Failed to find zap_log /zap/zap.out
ERROR <type 'exceptions.TypeError'>

**Command run :** 

stage('Scan Web Application') {
        def owasp_config_dir = "configFiles/owasp-zap-scan/"
        sh """
            cd ${owasp_config_dir}
            cp baseline-scan.conf /zap/wrk/
            /zap/zap-full-scan.py -d -m 5 -r baseline.html -c baseline-scan.conf -t <server_url>
        """
        publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: '/zap/wrk/', reportFiles: 'baseline.html', reportName: 'Zaproxy_Report', reportTitles: ''])
    }

**Comment by Aaqib041** [comment]
Hi Team,

Can someone please address the issue ?

Thanks

**Comment by InfoSec812** [comment]
This repository is deprecated and the current implementation can be found here: https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-agents/jenkins-agent-zap

**Comment by StephGit** [comment]
@Aaqib041
You have to update the python-scripts according to this change: https://github.com/zaproxy/zaproxy/pull/4120/files

@InfoSec812 In my opinion this issue still exists in the current implementation.

**Comment by InfoSec812** [comment]
@StephGit As mentioned previously, this repo is deprecated. If there is a problem, please open an issue in the new repo: https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-agents/jenkins-agent-zap
