### ISSUE TITLE
ImportError: No module named zapv2

### ISSUE THREAD

**Issue by Aaqib041** [rht-labs/owasp-zap-openshift#11]
Hi ,

I am getting below error when trying to run the scan. Please check.

Error :

Traceback (most recent call last):
  File "/zap/zap-baseline.py", line 54, in <module>
    from zapv2 import ZAPv2
ImportError: No module named zapv2

Command ran : 
+ /zap/zap-baseline.py -d -m 5 -r zaprpt.html -c baseline-scan.conf -t http://service-dev:8080

**Comment by InfoSec812** [comment]
Please note that at the top of the README for this repository, it is shown that it is **DEPRECATED**... We are no longer maintaining this repository. If you need a configuration to run OWASP ZAP in Kubernetes, I would recommend [this](https://github.com/redhat-cop/containers-quickstarts/tree/master/jenkins-agents/jenkins-agent-zap).
